/**/*:
  ros__parameters:
    broker:
      host: test.mosquitto.org
      port: 1883
    bridge:
      ros2mqtt:
        ros_topics:
          - /current_state
          - /ros2mqtt/grid_x_float
          - /ros2mqtt/grid_y_float
          - /ros2mqtt/grid_theta_float
        /current_state:
          mqtt_topic: step
          primitive: true
        /ros2mqtt/grid_x_float:
          mqtt_topic: xx
          primitive: true
        /ros2mqtt/grid_y_float:
          mqtt_topic: yy
          primitive: true
        /ros2mqtt/grid_theta_float:
          mqtt_topic: theta
          primitive: true
      # mqtt2ros:
      #   mqtt_topics:
      #     - pingpong/primitive
      #   pingpong/primitive:
      #     ros_topic: /pong/primitive
      #     primitive: true
